- name: Install and start Nginx
  hosts: web
  tasks:
  - name: Install Nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
