- name: addition
  hosts: web
  tasks:
  - name: addtion of two numbers
    ansible.builtin.set_fact:
      total_count: "{{ [ '{{ NUM1 }}','{{ NUM2 }}'] | sum }}"

  - name: Print the sum
    ansible.builtin.debug:
      msg: "The sum of the given number is {{ total_count }}"
