- name: Variable preference
  hosts: local
  connection: local
  vars:
    GREET: "PLAY LEVEL"
  vars_files:
  - course.yaml
  #vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: printing from task
    #vars:
      #GREET: " Task level"
    ansible.builtin.debug:
      msg: "I am from {{ GREET }}"