- name: Using condition to print
  hosts: local
  connection: local
  vars:
    my_number: 15
    u_number:10
  tasks:
  - name: print if greater than 10
    ansible.builtin.debug:
      msg: " the given number {{ my_number }} is greater than 10"
    when: my_number > 10
  - name: print if less than or equal to 10
    ansible.builtin.debug:
      msg: " the given {{ u_number }} is less than or equal to 10"
    when: u_number <= 10