- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls on shell module
    ansible.builtin.shell:  ls -ltr > /tmp/ouput.txt

  - name: execute ls command on command module
    ansible.builtin.command: lsss -ltrrrr
    register: command_result

  - name: print the result from command module
    ansible.builtin.debug:
      msg: " {{ command_result }}"
